version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./node_modules:/client/node_modules
      - ./:/client
    ports:
      - '3001:3001'
  client:
    build:
      dockerfile: Dockerfile.client
      context: ./
    depends_on:
      - server
    volumes:
      - ./app/node_modules:/client/node_modules
      - ./app:/client
    ports:
      - '3000:3000'