version: '3'
services:
  client:
    image: web-challenge/server
    depends_on:
      - server
    ports:
      - '3000:3000'
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./node_modules:/client/node_modules
      - ./:/client
    ports:
      - '3001:3001'